#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

command -v rsvg-convert >/dev/null 2>&1 || { echo "Error: rsvg-convert not found. Install librsvg (e.g. pacman -S librsvg, brew install librsvg)."; exit 1; }
command -v magick      >/dev/null 2>&1 || { echo "Error: magick not found. Install imagemagick."; exit 1; }

SRC="app icon.svg"
[[ -f "$SRC" ]] || { echo "Error: source file missing: $SRC"; exit 1; }

SET=ios/Runner/Assets.xcassets/AppIcon.appiconset
[[ -d "$SET" ]] || { echo "Error: $SET missing. Run 'flutter create --platforms=ios .' first."; exit 1; }

# Every size the asset catalogue asks for, read from the catalogue itself rather
# than restated here, so a Contents.json regenerated by a future flutter create
# stays in step. iOS rounds the corners itself and rejects any alpha, so these
# are drawn flat onto the icon's own background colour. - Opus 5
BG=$(python3 - <<'PY'
import re
svg = open("app icon.svg", encoding="utf-8", errors="replace").read()
m = re.search(r'pagecolor="(#[0-9a-fA-F]{6})"', svg)
print(m.group(1) if m else "#ffffff")
PY
)
echo "background: $BG"

python3 - "$SET" <<'PY' | while read -r px name; do
import json, sys
set_dir = sys.argv[1]
seen = set()
for i in json.load(open(f"{set_dir}/Contents.json"))["images"]:
    name = i.get("filename")
    if not name or name in seen:
        continue
    seen.add(name)
    side = float(i["size"].split("x")[0]) * float(i["scale"].rstrip("x"))
    print(int(round(side)), name)
PY
  rsvg-convert -w "$px" -h "$px" "$SRC" \
    | magick - -background "$BG" -alpha remove -alpha off "$SET/$name"
  echo "  -> $name (${px}x${px})"
done

echo "Done."
