name: makos_timer
description: "The most ergonomic timer app."
publish_to: "none"
license: "BSL-1.1(Apache-2.0, non-compete)"

version: 0.1.0

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  hsluv: ^1.1.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  nb_utils: ^7.1.4
  animove: ^1.4.0
  # animove:
  #   path: /home/mako/programming/animove/
  improved_wrap: ^2.0.0
  uuid: ^4.5.1
  # fixed to a specific older version until they fix https://github.com/simolus3/drift/issues/3682
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  collection: ^1.19.1
  signals: ^7.1.0
  # openhiit_audioplayers: ^1.0.0
  # there's a bug https://github.com/bluefireteam/audioplayers/issues/1749 on linux, random delay when starting playback for the second time, maintainers say they'll get to it.
  audioplayers: ^6.5.1
  # workmanager: ^0.9.0+3
  # flutter_soloud: ^3.3.6
  path: ^1.9.1
  drift_dev: ^2.28.3
  flutter_ringtone_manager: ^1.1.2
  flutter_refresh_rate_control: ^0.0.4+1
  screen_corner_radius: ^3.0.0
  # liquid_glass_renderer: ^0.2.0-dev.4
  vibration: ^3.1.8
  shadow_widget: ^0.1.1
  flutter_svg: ^2.0.9
  just_liquid_glass: ^0.8.0
  flutter_markdown_plus: ^1.0.3
  markdown: ^7.3.1
  url_launcher: ^6.3.1
  dynamic_color: ^1.8.1
  material_color_utilities: ^0.13.0
  universal_back_gesture: ^2.1.0

# dependency_overrides:
#   just_liquid_glass:
#     path: ../just_liquid_glass

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/jingles_STEEL15.wav
    - assets/sounds/jingles_STEEL16.wav
    - assets/sounds/june_russel_mako_timer_e-piano_1.wav
    - assets/sounds/silent.wav
    - assets/about.md
    - assets/how_made.md
    - assets/qr_code.svg

  fonts:
    - family: Dongle
      fonts:
        - asset: assets/fonts/Dongle-Regular.ttf
          weight: 400
        - asset: assets/fonts/Dongle-Bold.ttf
          weight: 700
