// (generated by claude)

package org.dreamshrine.makos_timer

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.util.Log
import androidx.core.content.ContextCompat

/**
 * Restarts the foreground service after a reboot or an app update, so timers that
 * were still pending survive — replacing flutter_foreground_task's RebootReceiver.
 * Only restarts if there's a persisted Dart callback handle (i.e. the service has
 * run before) and the user didn't intentionally stop it.
 */
class BootReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context?, intent: Intent?) {
        if (context == null || intent == null) return

        val shouldStart = when (intent.action) {
            Intent.ACTION_BOOT_COMPLETED,
            "android.intent.action.QUICKBOOT_POWERON",
            Intent.ACTION_MY_PACKAGE_REPLACED -> true
            else -> false
        }
        if (!shouldStart) return

        if (MakosTimerForegroundService.wasStoppedByUser(context)) return
        val handle = MakosTimerForegroundService.readCallbackHandle(context)
        if (handle == 0L) return

        try {
            val serviceIntent =
                Intent(context, MakosTimerForegroundService::class.java).apply {
                    action = MakosTimerForegroundService.ACTION_START
                    putExtra(MakosTimerForegroundService.EXTRA_CALLBACK_HANDLE, handle)
                    putExtra(MakosTimerForegroundService.EXTRA_IS_API_START, false)
                }
            ContextCompat.startForegroundService(context, serviceIntent)
        } catch (e: Exception) {
            Log.e("MakosTimerBoot", "failed to start service on ${intent.action}", e)
        }
    }
}
