// (generated by claude)

package org.dreamshrine.makos_timer

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import androidx.core.app.NotificationManagerCompat

/**
 * Fires when the user swipes away the persistent foreground-service notification
 * (Android 14+ allows dismissing foreground-service notifications). We treat that
 * as a deliberate "shut it down" gesture: stop the service — which tears down the
 * background isolate (releasing the audio player, so any sounding alarm stops) and
 * halts timer tracking — clear any alarm/completion notifications, and mark it
 * stopped so it doesn't auto-restart on reboot. It comes back the next time the
 * app is opened.
 */
class ForegroundDismissReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        MakosTimerForegroundService.markStopped(context, true)
        NotificationManagerCompat.from(context).cancelAll()
        context.stopService(
            Intent(context, MakosTimerForegroundService::class.java),
        )
    }
}
