// (generated by claude)

package org.dreamshrine.makos_timer

import android.Manifest
import android.app.Activity
import android.app.AlarmManager
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Build
import android.os.PowerManager
import android.provider.Settings
import androidx.core.app.ActivityCompat
import androidx.core.app.NotificationManagerCompat
import androidx.core.content.ContextCompat
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.embedding.engine.plugins.activity.ActivityAware
import io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.common.MethodChannel.MethodCallHandler
import io.flutter.plugin.common.MethodChannel.Result
import io.flutter.plugin.common.PluginRegistry

/**
 * Main-engine control surface for [MakosTimerForegroundService] — the
 * app-isolate side of what flutter_foreground_task's method channel used to do.
 * Drives start/stop/isRunning, and wraps the runtime permission / settings flows
 * the app needs (notifications, battery optimization, exact alarms) so we don't
 * pull in the package just for those helpers.
 *
 * Only ever attached to the main engine (it needs an Activity for the permission
 * dialogs). The foreground engine talks to the service over its own channel
 * (see [MakosTimerForegroundService.TASK_CHANNEL]).
 */
class ForegroundControlPlugin :
    FlutterPlugin,
    MethodCallHandler,
    ActivityAware,
    PluginRegistry.RequestPermissionsResultListener,
    PluginRegistry.ActivityResultListener {

    private lateinit var channel: MethodChannel
    private lateinit var context: Context

    private var activity: Activity? = null
    private var activityBinding: ActivityPluginBinding? = null

    private var pendingNotificationResult: Result? = null
    private var pendingBatteryResult: Result? = null
    private var pendingExactAlarmResult: Result? = null

    companion object {
        const val CHANNEL = "makos_timer/foreground"

        private const val REQ_NOTIFICATION = 0x4D01
        private const val REQ_BATTERY = 0x4D02
        private const val REQ_EXACT_ALARM = 0x4D03
    }

    override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        context = binding.applicationContext
        channel = MethodChannel(binding.binaryMessenger, CHANNEL)
        channel.setMethodCallHandler(this)
    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        channel.setMethodCallHandler(null)
    }

    override fun onMethodCall(call: MethodCall, result: Result) {
        when (call.method) {
            "start" -> {
                val handle = (call.argument<Number>("callbackHandle"))?.toLong()
                val isApiStart = call.argument<Boolean>("isApiStart") ?: true
                if (handle == null || handle == 0L) {
                    result.error("NO_HANDLE", "callbackHandle is required", null)
                    return
                }
                MakosTimerForegroundService.persistCallbackHandle(context, handle)
                val intent = Intent(context, MakosTimerForegroundService::class.java).apply {
                    action = MakosTimerForegroundService.ACTION_START
                    putExtra(MakosTimerForegroundService.EXTRA_CALLBACK_HANDLE, handle)
                    putExtra(MakosTimerForegroundService.EXTRA_IS_API_START, isApiStart)
                }
                ContextCompat.startForegroundService(context, intent)
                result.success(null)
            }
            "stop" -> {
                MakosTimerForegroundService.markStopped(context, true)
                context.stopService(
                    Intent(context, MakosTimerForegroundService::class.java),
                )
                result.success(null)
            }
            "isRunning" -> result.success(MakosTimerForegroundService.isRunning)
            "update" -> {
                MakosTimerForegroundService.pushNotification(
                    call.argument<String>("title"),
                    call.argument<String>("text"),
                )
                result.success(null)
            }
            "checkNotificationPermission" ->
                result.success(if (areNotificationsGranted()) "granted" else "denied")
            "requestNotificationPermission" -> requestNotificationPermission(result)
            "isIgnoringBatteryOptimizations" ->
                result.success(isIgnoringBatteryOptimizations())
            "requestIgnoreBatteryOptimization" -> requestIgnoreBatteryOptimization(result)
            "canScheduleExactAlarms" -> result.success(canScheduleExactAlarms())
            "openAlarmsAndRemindersSettings" -> openExactAlarmSettings(result)
            else -> result.notImplemented()
        }
    }

    // --- notifications ---

    private fun areNotificationsGranted(): Boolean {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            return ContextCompat.checkSelfPermission(
                context,
                Manifest.permission.POST_NOTIFICATIONS,
            ) == PackageManager.PERMISSION_GRANTED
        }
        return NotificationManagerCompat.from(context).areNotificationsEnabled()
    }

    private fun requestNotificationPermission(result: Result) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) {
            result.success(if (areNotificationsGranted()) "granted" else "denied")
            return
        }
        if (areNotificationsGranted()) {
            result.success("granted")
            return
        }
        val act = activity
        if (act == null) {
            result.error("NO_ACTIVITY", "Activity not attached", null)
            return
        }
        if (pendingNotificationResult != null) {
            result.error("IN_PROGRESS", "A permission request is already in progress", null)
            return
        }
        pendingNotificationResult = result
        ActivityCompat.requestPermissions(
            act,
            arrayOf(Manifest.permission.POST_NOTIFICATIONS),
            REQ_NOTIFICATION,
        )
    }

    override fun onRequestPermissionsResult(
        requestCode: Int,
        permissions: Array<out String>,
        grantResults: IntArray,
    ): Boolean {
        if (requestCode != REQ_NOTIFICATION) return false
        val result = pendingNotificationResult ?: return true
        pendingNotificationResult = null
        val granted = grantResults.isNotEmpty() &&
            grantResults[0] == PackageManager.PERMISSION_GRANTED
        result.success(if (granted) "granted" else "denied")
        return true
    }

    // --- battery optimization ---

    private fun isIgnoringBatteryOptimizations(): Boolean {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) return true
        val pm = context.getSystemService(Context.POWER_SERVICE) as PowerManager
        return pm.isIgnoringBatteryOptimizations(context.packageName)
    }

    private fun requestIgnoreBatteryOptimization(result: Result) {
        if (isIgnoringBatteryOptimizations()) {
            result.success(true)
            return
        }
        val act = activity
        if (act == null) {
            result.error("NO_ACTIVITY", "Activity not attached", null)
            return
        }
        if (pendingBatteryResult != null) {
            result.error("IN_PROGRESS", "A request is already in progress", null)
            return
        }
        pendingBatteryResult = result
        @Suppress("BatteryLife")
        val intent = Intent(
            Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,
            Uri.parse("package:${context.packageName}"),
        )
        try {
            act.startActivityForResult(intent, REQ_BATTERY)
        } catch (e: Exception) {
            pendingBatteryResult = null
            result.error("LAUNCH_FAILED", e.message, null)
        }
    }

    // --- exact alarms ---

    private fun canScheduleExactAlarms(): Boolean {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.S) return true
        val am = context.getSystemService(Context.ALARM_SERVICE) as AlarmManager
        return am.canScheduleExactAlarms()
    }

    private fun openExactAlarmSettings(result: Result) {
        if (canScheduleExactAlarms() || Build.VERSION.SDK_INT < Build.VERSION_CODES.S) {
            result.success(true)
            return
        }
        val act = activity
        if (act == null) {
            result.error("NO_ACTIVITY", "Activity not attached", null)
            return
        }
        if (pendingExactAlarmResult != null) {
            result.error("IN_PROGRESS", "A request is already in progress", null)
            return
        }
        pendingExactAlarmResult = result
        val intent = Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM).apply {
            data = Uri.parse("package:${context.packageName}")
        }
        try {
            act.startActivityForResult(intent, REQ_EXACT_ALARM)
        } catch (e: Exception) {
            pendingExactAlarmResult = null
            result.error("LAUNCH_FAILED", e.message, null)
        }
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?): Boolean {
        when (requestCode) {
            REQ_BATTERY -> {
                val result = pendingBatteryResult ?: return true
                pendingBatteryResult = null
                result.success(isIgnoringBatteryOptimizations())
                return true
            }
            REQ_EXACT_ALARM -> {
                val result = pendingExactAlarmResult ?: return true
                pendingExactAlarmResult = null
                result.success(canScheduleExactAlarms())
                return true
            }
        }
        return false
    }

    // --- activity lifecycle ---

    override fun onAttachedToActivity(binding: ActivityPluginBinding) {
        activity = binding.activity
        activityBinding = binding
        binding.addRequestPermissionsResultListener(this)
        binding.addActivityResultListener(this)
    }

    override fun onDetachedFromActivityForConfigChanges() = detachActivity()

    override fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding) =
        onAttachedToActivity(binding)

    override fun onDetachedFromActivity() = detachActivity()

    private fun detachActivity() {
        activityBinding?.removeRequestPermissionsResultListener(this)
        activityBinding?.removeActivityResultListener(this)
        activity = null
        activityBinding = null
    }
}
