// (generated by claude)

package org.dreamshrine.makos_timer

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.app.Service
import android.content.Context
import android.content.Intent
import android.content.pm.ServiceInfo
import android.os.Build
import android.os.IBinder
import android.os.PowerManager
import androidx.core.app.NotificationCompat
import io.flutter.FlutterInjector
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.embedding.engine.dart.DartExecutor
import io.flutter.embedding.engine.loader.FlutterLoader
import io.flutter.plugin.common.MethodChannel
import io.flutter.view.FlutterCallbackInformation

/**
 * Self-owned foreground service that replaces flutter_foreground_task. It hosts a
 * headless Flutter engine (running the [foregroundTaskStart] Dart entry point) so
 * timers keep running while the app is gone, and renders the persistent
 * notification — which we now control fully (mono small icon, no forced
 * BigTextStyle / expand when idle, no app-name-duplicating title).
 *
 * Engine bootstrap mirrors flutter_foreground_task's ForegroundTask: create a
 * [FlutterEngine] (which auto-registers GeneratedPluginRegistrant), ensure the
 * loader is initialized, register the app's custom plugins, then execute the Dart
 * callback looked up from a persisted handle.
 *
 * Comms with the Dart side go over the [TASK_CHANNEL] MethodChannel on the task
 * engine's messenger:
 *   Dart -> native: "ready" (returns isApiStart), "update" (title/text), "stop".
 *   native -> Dart: "destroy" (run teardown before the engine is destroyed).
 * App<->task data (hello/heartbeat/goodbye/dismissAlarms) goes over IsolateNameServer
 * ports instead, exactly as the dismissAlarms path already did.
 */
class MakosTimerForegroundService : Service() {
    private var flutterEngine: FlutterEngine? = null
    private var taskChannel: MethodChannel? = null
    private var pendingIsApiStart: Boolean = false
    private var wakeLock: PowerManager.WakeLock? = null

    companion object {
        const val ACTION_START = "org.dreamshrine.makos_timer.action.START"
        const val ACTION_STOP = "org.dreamshrine.makos_timer.action.STOP"

        const val EXTRA_CALLBACK_HANDLE = "callback_handle"
        const val EXTRA_IS_API_START = "is_api_start"

        const val TASK_CHANNEL = "makos_timer/foreground_task"

        const val NOTIFICATION_ID = 1
        const val CHANNEL_ID = "foreground_service"
        const val CHANNEL_NAME = "mako timer's persistent notification"

        private const val WAKE_LOCK_TAG = "makos_timer:completion_wakelock"

        private const val PREFS = "makos_timer_fgs"
        private const val PREF_CALLBACK_HANDLE = "callback_handle"
        private const val PREF_STOPPED = "stopped_by_user"

        // The live Service instance while it's running, so the control plugin can
        // answer isRunning() and push notification updates (from the main isolate)
        // without binding.
        @Volatile
        var runningInstance: MakosTimerForegroundService? = null
            private set

        val isRunning: Boolean
            get() = runningInstance != null

        /** Update the persistent notification if the service is running (no-op otherwise). */
        fun pushNotification(title: String?, text: String?) {
            runningInstance?.updateNotification(title, text)
        }

        fun persistCallbackHandle(context: Context, handle: Long) {
            context.getSharedPreferences(PREFS, Context.MODE_PRIVATE).edit()
                .putLong(PREF_CALLBACK_HANDLE, handle)
                .putBoolean(PREF_STOPPED, false)
                .apply()
        }

        fun readCallbackHandle(context: Context): Long {
            val prefs = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            return if (prefs.contains(PREF_CALLBACK_HANDLE)) {
                prefs.getLong(PREF_CALLBACK_HANDLE, 0L)
            } else {
                0L
            }
        }

        /** The user/app intentionally stopped the service; don't auto-restart on boot. */
        fun markStopped(context: Context, stopped: Boolean) {
            context.getSharedPreferences(PREFS, Context.MODE_PRIVATE).edit()
                .putBoolean(PREF_STOPPED, stopped)
                .apply()
        }

        fun wasStoppedByUser(context: Context): Boolean =
            context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
                .getBoolean(PREF_STOPPED, false)
    }

    override fun onBind(intent: Intent?): IBinder? = null

    override fun onCreate() {
        super.onCreate()
        createNotificationChannel()
        runningInstance = this
        acquireWakeLock()
    }

    // Without this, the CPU is free to suspend once the screen's been off for a
    // while, which stalls the completion Timer (see enlivenTimer in main.dart)
    // regardless of the timer's duration — it only resumes once something else
    // happens to wake the CPU. Holding a partial wake lock for the service's
    // lifetime (mirroring flutter_foreground_task's allowWakeLock, which this
    // service replaced) keeps completions on schedule.
    private fun acquireWakeLock() {
        if (wakeLock?.isHeld == true) return
        val pm = getSystemService(Context.POWER_SERVICE) as PowerManager
        wakeLock = pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK, WAKE_LOCK_TAG).apply {
            setReferenceCounted(false)
            acquire()
        }
    }

    private fun releaseWakeLock() {
        wakeLock?.let { if (it.isHeld) it.release() }
        wakeLock = null
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        when (intent?.action) {
            ACTION_STOP -> {
                stopForegroundCompat()
                stopSelf()
                return START_NOT_STICKY
            }
            else -> {
                // ACTION_START, or a null intent (START_STICKY restart after kill).
                // Promote to foreground promptly with the idle notification, then
                // bootstrap the engine if it isn't already up.
                startForegroundCompat(buildNotification(null, null))

                val isApiStart = intent?.getBooleanExtra(EXTRA_IS_API_START, false) ?: false
                val handle = intent?.getLongExtra(EXTRA_CALLBACK_HANDLE, 0L)
                    ?.takeIf { it != 0L }
                    ?: readCallbackHandle(this)
                if (handle != 0L) {
                    persistCallbackHandle(this, handle)
                }
                if (flutterEngine == null && handle != 0L) {
                    pendingIsApiStart = isApiStart
                    bootstrapEngine(handle)
                }
            }
        }
        return START_STICKY
    }

    override fun onTaskRemoved(rootIntent: Intent?) {
        // The user swiped the app away from recents. The main isolate is dying;
        // tell the foreground isolate to take over tracking immediately instead of
        // waiting out its heartbeat timeout. (stopWithTask=false keeps us running.)
        taskChannel?.invokeMethod("appKilled", null)
        super.onTaskRemoved(rootIntent)
    }

    private fun bootstrapEngine(callbackHandle: Long) {
        val engine = FlutterEngine(this)
        flutterEngine = engine

        val loader: FlutterLoader = FlutterInjector.instance().flutterLoader()
        if (!loader.initialized()) {
            loader.startInitialization(applicationContext)
        }
        loader.ensureInitializationComplete(applicationContext, null)

        // GeneratedPluginRegistrant is registered automatically by the FlutterEngine
        // constructor; the custom (non-pub) plugins must be added by hand — this is
        // what CustomPluginRegistrant used to do for the foreground engine.
        engine.plugins.add(PlatformAudioPlugin())
        engine.plugins.add(PlatformNotificationPlugin())

        val channel = MethodChannel(engine.dartExecutor.binaryMessenger, TASK_CHANNEL)
        channel.setMethodCallHandler { call, result ->
            when (call.method) {
                "ready" -> result.success(pendingIsApiStart)
                "update" -> {
                    updateNotification(
                        call.argument<String>("title"),
                        call.argument<String>("text"),
                    )
                    result.success(null)
                }
                "stop" -> {
                    result.success(null)
                    stopForegroundCompat()
                    stopSelf()
                }
                else -> result.notImplemented()
            }
        }
        taskChannel = channel

        val bundlePath = loader.findAppBundlePath()
        val callbackInfo = FlutterCallbackInformation.lookupCallbackInformation(callbackHandle)
        if (callbackInfo == null) {
            // Stale/invalid handle (e.g. after a hot reinstall) — nothing to run.
            flutterEngine = null
            taskChannel = null
            return
        }
        val dartCallback = DartExecutor.DartCallback(assets, bundlePath, callbackInfo)
        engine.dartExecutor.executeDartCallback(dartCallback)
    }

    private fun updateNotification(title: String?, text: String?) {
        val manager = getSystemService(NotificationManager::class.java)
        manager.notify(NOTIFICATION_ID, buildNotification(title, text))
    }

    private fun buildNotification(title: String?, text: String?): Notification {
        val launchIntent = packageManager.getLaunchIntentForPackage(packageName)
        val contentIntent = launchIntent?.let {
            PendingIntent.getActivity(
                this,
                0,
                it,
                PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE,
            )
        }

        // Fires when the user swipes the notification away (Android 14+) — handled
        // by ForegroundDismissReceiver, which stops the whole service.
        val deleteIntent = PendingIntent.getBroadcast(
            this,
            0,
            Intent(this, ForegroundDismissReceiver::class.java),
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE,
        )

        val builder = NotificationCompat.Builder(this, CHANNEL_ID)
            .setSmallIcon(resId("res_notification_icon"))
            .setOngoing(true)
            .setOnlyAlertOnce(true)
            .setSilent(true)
            .setContentIntent(contentIntent)
            .setDeleteIntent(deleteIntent)

        if (!title.isNullOrEmpty()) {
            builder.setContentTitle(title)
        }
        if (!text.isNullOrEmpty()) {
            builder.setContentText(text)
            // Only attach a big style (which makes the notification expandable) when
            // there's actually multi-line content to reveal. Idle = icon-only and not
            // expandable.
            builder.setStyle(NotificationCompat.BigTextStyle().bigText(text))
        }

        return builder.build()
    }

    private fun createNotificationChannel() {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return
        val manager = getSystemService(NotificationManager::class.java)
        if (manager.getNotificationChannel(CHANNEL_ID) == null) {
            val channel = NotificationChannel(
                CHANNEL_ID,
                CHANNEL_NAME,
                NotificationManager.IMPORTANCE_LOW,
            ).apply {
                description = CHANNEL_NAME
                setShowBadge(false)
                setSound(null, null)
                enableVibration(false)
            }
            manager.createNotificationChannel(channel)
        }
    }

    private fun startForegroundCompat(notification: Notification) {
        try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                startForeground(
                    NOTIFICATION_ID,
                    notification,
                    ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE,
                )
            } else {
                startForeground(NOTIFICATION_ID, notification)
            }
        } catch (e: Exception) {
            // e.g. ForegroundServiceStartNotAllowedException when started from the
            // background on Android 12+. Nothing actionable here; the next app
            // foreground will start it again.
            android.util.Log.e("MakosTimerFGS", "startForeground failed", e)
        }
    }

    @Suppress("DEPRECATION")
    private fun stopForegroundCompat() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            stopForeground(STOP_FOREGROUND_REMOVE)
        } else {
            stopForeground(true)
        }
    }

    override fun onDestroy() {
        if (runningInstance === this) runningInstance = null
        releaseWakeLock()
        val engine = flutterEngine
        val channel = taskChannel
        if (engine != null && channel != null) {
            // Let the Dart side run its teardown, then destroy the engine.
            channel.invokeMethod("destroy", false, object : MethodChannel.Result {
                override fun success(result: Any?) = destroyEngine()
                override fun error(code: String, msg: String?, details: Any?) = destroyEngine()
                override fun notImplemented() = destroyEngine()
            })
        } else {
            destroyEngine()
        }
        super.onDestroy()
    }

    private fun destroyEngine() {
        taskChannel?.setMethodCallHandler(null)
        taskChannel = null
        flutterEngine?.destroy()
        flutterEngine = null
    }

    private fun resId(name: String, type: String = "drawable"): Int =
        resources.getIdentifier(name, type, packageName)
}
