// (generated by claude)

package org.dreamshrine.makos_timer

import android.content.Context
import android.database.Cursor
import android.media.AudioAttributes
import android.media.AudioFocusRequest
import android.media.AudioManager
import android.media.MediaPlayer
import android.media.RingtoneManager
import android.media.RingtoneManager.TYPE_ALARM
import android.media.RingtoneManager.TYPE_NOTIFICATION
import android.media.RingtoneManager.TYPE_RINGTONE
import android.net.Uri
import android.os.Build
import android.os.Handler
import android.os.Looper
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.common.MethodChannel.MethodCallHandler
import io.flutter.plugin.common.MethodChannel.Result
import java.util.concurrent.Executors

class PlatformAudioPlugin : FlutterPlugin, MethodCallHandler {
    private lateinit var channel: MethodChannel
    private lateinit var context: Context
    private lateinit var audioManager: AudioManager
    private var mediaPlayer: MediaPlayer? = null
    private var audioFocusRequest: AudioFocusRequest? = null
    private val executor = Executors.newSingleThreadExecutor()
    private val mainHandler = Handler(Looper.getMainLooper())

    override fun onAttachedToEngine(flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
        channel = MethodChannel(flutterPluginBinding.binaryMessenger, "platform_audio")
        channel.setMethodCallHandler(this)
        context = flutterPluginBinding.applicationContext
        audioManager = context.getSystemService(Context.AUDIO_SERVICE) as AudioManager
    }

    override fun onMethodCall(call: MethodCall, result: Result) {
        when (call.method) {
            "getPlatformAudio" -> {
                val type = call.argument<String>("type")
                if (type != null) {
                    executor.execute {
                        try {
                            val audioList = getPlatformAudio(type)
                            mainHandler.post {
                                result.success(audioList)
                            }
                        } catch (e: Exception) {
                            mainHandler.post {
                                result.error("QUERY_FAILED", "Failed to query platform audio: ${e.message}", null)
                            }
                        }
                    }
                } else {
                    result.error("INVALID_ARGUMENT", "type cannot be null", null)
                }
            }
            "getDefaultAudio" -> {
                val type = call.argument<String>("type")
                if (type != null) {
                    val defaultAudio = getDefaultAudio(type)
                    result.success(defaultAudio)
                } else {
                    result.error("INVALID_ARGUMENT", "type cannot be null", null)
                }
            }
            "playAudio" -> {
                val uri = call.argument<String>("uri")
                playAudio(uri, result, looping = false)
            }
            "playAudioLooping" -> {
                val uri = call.argument<String>("uri")
                playAudio(uri, result, looping = true)
            }
            "pauseAudio" -> {
                pauseAudio()
                result.success(null)
            }
            "stopAudio" -> {
                stopAudio()
                result.success(null)
            }
            else -> {
                result.notImplemented()
            }
        }
    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        channel.setMethodCallHandler(null)
        executor.shutdown()
    }

    private fun stringToRingtoneType(typeString: String): Int? {
        return when (typeString) {
            "ringtone" -> TYPE_RINGTONE
            "notification" -> TYPE_NOTIFICATION
            "alarm" -> TYPE_ALARM
            else -> null
        }
    }

    private fun getDefaultAudio(typeString: String): Map<String, Any?>? {
        val type = stringToRingtoneType(typeString) ?: return null
        val isLong = type != TYPE_NOTIFICATION

        val uri = RingtoneManager.getActualDefaultRingtoneUri(context, type)

        if (uri == null) {
            // Silent is the default
            return mapOf(
                "uri" to null,
                "name" to "Silent",
                "isLong" to isLong
            )
        }

        val ringtone = RingtoneManager.getRingtone(context, uri)
        val title = ringtone?.getTitle(context) ?: "Unknown"

        return mapOf(
            "uri" to uri.toString(),
            "name" to title,
            "isLong" to isLong
        )
    }

    private fun getPlatformAudio(typeString: String): List<Map<String, Any?>> {
        val type = stringToRingtoneType(typeString) ?: return emptyList()
        val isLong = type != TYPE_NOTIFICATION
        val ringtoneManager = RingtoneManager(context)
        ringtoneManager.setType(type)

        val audioList = mutableListOf<Map<String, Any?>>()

        val cursor: Cursor = ringtoneManager.cursor
        try {
            while (cursor.moveToNext()) {
                val title = cursor.getString(RingtoneManager.TITLE_COLUMN_INDEX)
                val uri = ringtoneManager.getRingtoneUri(cursor.position)

                audioList.add(
                    mapOf(
                        "uri" to uri.toString(),
                        "name" to title,
                        "isLong" to isLong
                    )
                )
            }
        } finally {
            cursor.close()
        }

        return audioList
    }

    private fun playAudio(uriString: String?, result: Result, looping: Boolean = false) {
        try {
            stopAudio()  // Clean up previous player

            if (uriString == null) {
                result.success(null)
                return
            }

            // Request audio focus - this pauses other audio
            val focusResult = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                val audioAttributes = AudioAttributes.Builder()
                    .setUsage(AudioAttributes.USAGE_ALARM)
                    .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                    .build()

                audioFocusRequest = AudioFocusRequest.Builder(AudioManager.AUDIOFOCUS_GAIN_TRANSIENT)
                    .setAudioAttributes(audioAttributes)
                    .setAcceptsDelayedFocusGain(false)
                    .setWillPauseWhenDucked(false)
                    .setOnAudioFocusChangeListener { }
                    .build()

                audioManager.requestAudioFocus(audioFocusRequest!!)
            } else {
                @Suppress("DEPRECATION")
                audioManager.requestAudioFocus(
                    { },
                    AudioManager.STREAM_ALARM,
                    AudioManager.AUDIOFOCUS_GAIN_TRANSIENT
                )
            }

            if (focusResult == AudioManager.AUDIOFOCUS_REQUEST_GRANTED) {
                mediaPlayer = MediaPlayer().apply {
                    // Handle different URI types
                    if (uriString.startsWith("asset://")) {
                        // Flutter asset - use AssetFileDescriptor
                        val assetPath = "flutter_assets/" + uriString.removePrefix("asset://")
                        val afd = context.assets.openFd(assetPath)
                        setDataSource(afd.fileDescriptor, afd.startOffset, afd.length)
                        afd.close()
                    } else {
                        // content://, file://, or other URIs
                        val uri = Uri.parse(uriString)
                        setDataSource(context, uri)
                    }

                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                        setAudioAttributes(
                            AudioAttributes.Builder()
                                .setUsage(AudioAttributes.USAGE_ALARM)
                                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                                .build()
                        )
                    } else {
                        @Suppress("DEPRECATION")
                        setAudioStreamType(AudioManager.STREAM_ALARM)
                    }

                    isLooping = looping

                    if (!looping) {
                        setOnCompletionListener {
                            abandonAudioFocus()
                        }
                    }

                    prepare()
                    start()
                }
                result.success(null)
            } else {
                result.error("FOCUS_FAILED", "Failed to gain audio focus", null)
            }
        } catch (e: Exception) {
            e.printStackTrace()
            abandonAudioFocus()
            result.error("PLAY_FAILED", "Failed to play audio: ${e.message}", null)
        }
    }

    private fun pauseAudio() {
        mediaPlayer?.apply {
            if (isPlaying) pause()
        }
    }

    private fun stopAudio() {
        mediaPlayer?.apply {
            if (isPlaying) stop()
            release()
        }
        mediaPlayer = null
        abandonAudioFocus()
    }

    private fun abandonAudioFocus() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            audioFocusRequest?.let { audioManager.abandonAudioFocusRequest(it) }
        } else {
            @Suppress("DEPRECATION")
            audioManager.abandonAudioFocus { }
        }
    }
}
