// (generated by claude)

package org.dreamshrine.makos_timer

import android.app.Activity
import android.content.Intent
import android.os.Bundle
import android.provider.AlarmClock

/**
 * Catches the system's timer intents — what Assistant sends for "set a timer for
 * five minutes", "show my timers", "stop the timer".
 *
 * It exists separately from [MainActivity] because SET_TIMER can ask (via
 * EXTRA_SKIP_UI) for the timer to just start, without an app appearing; a
 * FlutterActivity can't honour that, since being on screen is the whole point of
 * it. So this is a windowless relay: it reads the intent, hands it to
 * [TimerIntentPlugin], launches the app only if the request actually wants to be
 * seen, and finishes before it ever draws.
 */
class TimerIntentActivity : Activity() {
    @Suppress("DEPRECATION") // overridePendingTransition's replacement is API 34
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        route(intent)
        finish()
        overridePendingTransition(0, 0)
    }

    private fun route(source: Intent?) {
        val intent = source ?: return
        // ACTION_SHOW_TIMERS / ACTION_DISMISS_TIMER are API 26 string constants;
        // spelled out here so they read the same as the manifest's filters.
        val (payload, headless) = when (intent.action) {
            AlarmClock.ACTION_SET_TIMER -> {
                val seconds = intent.getIntExtra(AlarmClock.EXTRA_LENGTH, 0)
                Pair(
                    mapOf<String, Any?>(
                        "action" to "setTimer",
                        "seconds" to seconds,
                        "message" to intent.getStringExtra(AlarmClock.EXTRA_MESSAGE),
                    ),
                    // No length means "open the timer UI so the user can enter
                    // one", which no amount of skipping UI can accomplish.
                    seconds > 0 &&
                        intent.getBooleanExtra(AlarmClock.EXTRA_SKIP_UI, false),
                )
            }
            "android.intent.action.SHOW_TIMERS" ->
                Pair(mapOf<String, Any?>("action" to "showTimers"), false)
            // Silencing an alarm by voice shouldn't drag the app up in front of
            // whatever the user was doing, so this one is never shown.
            "android.intent.action.DISMISS_TIMER" ->
                Pair(mapOf<String, Any?>("action" to "dismissTimer"), true)
            else -> return
        }

        if (headless && TimerIntentPlugin.deliverHeadless(this, payload)) return

        TimerIntentPlugin.deliverToApp(payload)
        val launch = packageManager.getLaunchIntentForPackage(packageName) ?: return
        startActivity(launch)
    }
}
