// (generated by claude)

package org.dreamshrine.makos_timer

import android.content.Context
import android.content.Intent
import android.util.Log
import androidx.core.content.ContextCompat
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.common.MethodChannel.MethodCallHandler
import io.flutter.plugin.common.MethodChannel.Result

/**
 * Carries the alarm-clock intents that [TimerIntentActivity] catches into
 * whichever Flutter isolate currently owns the mobj registry.
 *
 * Routing rests on one invariant: the main isolate heartbeats the service for as
 * long as its process is alive, so the service isolate has relinquished the
 * registry whenever the main engine is attached. Hence "main engine attached =>
 * the main isolate takes it; otherwise wake the service and let its isolate".
 *
 * Registered on both engines, and both directions are lossless: a payload that
 * arrives before its target's Dart handler exists waits in that target's queue
 * until the handler announces itself with 'consumePending'.
 */
class TimerIntentPlugin(private val isMainEngine: Boolean) :
    FlutterPlugin,
    MethodCallHandler {

    private lateinit var channel: MethodChannel

    companion object {
        const val CHANNEL = "makos_timer/timer_intent"

        // Only ever touched from the platform thread (plugin attach/detach,
        // method calls, and TimerIntentActivity.onCreate all run there).
        private var mainChannel: MethodChannel? = null
        private var serviceChannel: MethodChannel? = null
        private val pendingMain = ArrayDeque<Map<String, Any?>>()
        private val pendingService = ArrayDeque<Map<String, Any?>>()

        /** True once that engine's Dart side has installed its call handler. */
        private var mainReady = false
        private var serviceReady = false

        /**
         * Hands [payload] to whoever can act on it without showing the app.
         * Returns false when nobody can — no live main engine and no persisted
         * service callback to wake — which means the caller has to fall back to
         * launching the app.
         */
        fun deliverHeadless(context: Context, payload: Map<String, Any?>): Boolean {
            if (mainChannel != null) {
                pendingMain.addLast(payload)
                flushMain()
                return true
            }
            if (!MakosTimerForegroundService.isRunning && !wakeService(context)) return false
            pendingService.addLast(payload)
            flushService()
            return true
        }

        /** Hands [payload] to the main isolate; the caller is launching the app for it. */
        fun deliverToApp(payload: Map<String, Any?>) {
            pendingMain.addLast(payload)
            flushMain()
        }

        private fun wakeService(context: Context): Boolean {
            // 0 means the service has never run, so there's no Dart entry point to
            // look up — the app has to be opened at least once first.
            val handle = MakosTimerForegroundService.readCallbackHandle(context)
            if (handle == 0L) return false
            return try {
                ContextCompat.startForegroundService(
                    context,
                    Intent(context, MakosTimerForegroundService::class.java).apply {
                        action = MakosTimerForegroundService.ACTION_START
                        putExtra(MakosTimerForegroundService.EXTRA_CALLBACK_HANDLE, handle)
                        putExtra(MakosTimerForegroundService.EXTRA_IS_API_START, false)
                    },
                )
                true
            } catch (e: Exception) {
                Log.e("MakosTimerIntent", "failed to wake the service for an intent", e)
                false
            }
        }

        private fun flushMain() {
            val channel = mainChannel ?: return
            if (!mainReady) return
            while (pendingMain.isNotEmpty()) {
                channel.invokeMethod("timerIntent", pendingMain.removeFirst())
            }
        }

        private fun flushService() {
            val channel = serviceChannel ?: return
            if (!serviceReady) return
            while (pendingService.isNotEmpty()) {
                channel.invokeMethod("timerIntent", pendingService.removeFirst())
            }
        }
    }

    override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        channel = MethodChannel(binding.binaryMessenger, CHANNEL)
        channel.setMethodCallHandler(this)
        if (isMainEngine) mainChannel = channel else serviceChannel = channel
    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        channel.setMethodCallHandler(null)
        if (isMainEngine) {
            if (mainChannel === channel) mainChannel = null
            mainReady = false
        } else {
            if (serviceChannel === channel) serviceChannel = null
            serviceReady = false
        }
    }

    override fun onMethodCall(call: MethodCall, result: Result) {
        when (call.method) {
            "consumePending" -> {
                val queue = if (isMainEngine) pendingMain else pendingService
                val taken = queue.toList()
                queue.clear()
                if (isMainEngine) mainReady = true else serviceReady = true
                result.success(taken)
            }
            else -> result.notImplemented()
        }
    }
}
